* fix detection of valid address may stop the script
The | grep invalid may return an error when INVALID is not present in
the string. Due to the "set -e", the script was exiting with an error,
not updating the lists. Adding || true resolves the problem

diff --git a/add-ip b/add-ip
--- a/add-ip
+++ b/add-ip
@@ -37,7 +37,7 @@ then
 	exit 1
 fi
 
-isInvalid=$(echo $range | grep 'INVALID ADDRESS')
+isInvalid=$(echo $range | grep 'INVALID ADDRESS' || true)
 if [ ! -z "$isInvalid" ]
 then
 	#echo "And error occured while treating range '$inetnum'."
