* fix for inetnum already being cidr notation

diff --git a/add-ip b/add-ip
--- a/add-ip
+++ b/add-ip
@@ -33,13 +33,20 @@ then
 		netname="divers"
 	fi
 fi
-range=$(ipcalc $inetnum | grep -v deaggregate)
-if [ $? -ne 0 ]
+
+isCidr=$(echo $inetnum | grep '/' || true)
+if [ ! -z "$isCidr" ]
 then
-	echo "And error occured while treating range '$inetnum'."
-	echo "It returned :"
-	echo $range
-	exit 1
+	range=$inetnum
+else
+	range=$(ipcalc $inetnum | grep -v deaggregate)
+	if [ $? -ne 0 ]
+	then
+		echo "And error occured while treating range '$inetnum'."
+		echo "It returned :"
+		echo $range
+		exit 1
+	fi
 fi
 
 isInvalid=$(echo $range | grep 'INVALID ADDRESS' || true)
