* fix handle incomplete ip/mask
Sometimes we have 123.456/24 as ip, don't treat them.

diff --git a/add-ip b/add-ip
--- a/add-ip
+++ b/add-ip
@@ -22,9 +22,29 @@ fi
 netname=$(cat $whoisfile | grep -i netname: | head -n 1 | cut -d':' -f 2- | awk '{print $1; }')
 if [ -z "$netname" ]
 then
-	netname="divers"
+	netname=$(cat $whoisfile | grep -i aut-name | head -n 1 | cut -d':' -f 2- | awk '{ print $1; }')
+	if [ -z "$netname" ]
+	then
+		netname="divers"
+	fi
 fi
 range=$(ipcalc $inetnum | grep -v deaggregate)
+if [ $? -ne 0 ]
+then
+	echo "And error occured while treating range '$inetnum'."
+	echo "It returned :"
+	echo $range
+	exit 1
+fi
+
+isInvalid=$(echo $range | grep 'INVALID ADDRESS')
+if [ ! -z "$isInvalid" ]
+then
+	echo "And error occured while treating range '$inetnum'."
+	echo "It returned :"
+	echo $range
+	exit 1
+fi
 
 
 #echo "intenum: $inetnum"
